try:
    username = input("Username Here ==> ")
    social_sites = {
        "facebook": f"https://facebook.com/{username}",
        "youtube": f"https://youtube.com/{username}",
        "instagram": f"https://instagram.com/{username}",
        "vimeo": f"https://vimeo.com/{username}",
        "github": f"https://github.com/{username}",
        "plus": f"https://plus.google.com/{username}",
        "pinterest": f"https://pinterest.com/{username}",
        "flickr": f"https://flickr.com/people/{username}",
        "vk": f"https://vk.com/{username}",
        "about": f"https://about.me/{username}",
        "disqus": f"https://disqus.com/{username}",
        "bitbucket": f"https://bitbucket.org/{username}",
        "flipboard": f"https://flipboard.com/@{username}",
        "twitter": f"https://twitter.com/{username}",
        "medium": f"https://medium.com/@{username}",
        "hackerone": f"https://hackerone.com/{username}",
        "keybase": f"https://keybase.io/{username}",
        "buzzfeed": f"https://buzzfeed.com/{username}",
        "slideshare": f"https://slideshare.net/{username}",
        "soundcloud": f"https://soundcloud.com/{username}",
        "imgur": f"https://imgur.com/user/{username}",
        "spotify": f"https://open.spotify.com/user/{username}",
        "wattpad": f"https://wattpad.com/user/{username}",
        "canva": f"https://canva.com/{username}",
        "codecademy": f"https://codecademy.com/{username}",
        "cash": f"https://cash.me/{username}",
        "angel": f"https://angel.co/{username}",
        "wikipedia": f"https://www.wikipedia.org/wiki/User:{username}",
        "blogspot": f"https://{username}.blogspot.com/",
        "tumblr": f"https://{username}.tumblr.com/",
        "wordpress": f"https://{username}.wordpress.com/",
        "devianart": f"https://{username}.devianart.com/",
        "slack": f"https://{username}.slack.com/",
        "steamcommunity": f"https://steamcommunity.com/id/{username}",
        "freelancer": f"https://www.freelancer.com/u/{username}",
        "dailymotion": f"https://www.dailymotion.com/{username}",
        "instructables": f"https://www.instructables.com/member/{username}",
        "etsy": f"https://www.etsy.com/shop/{username}",
        "patreon": f"https://www.patreon.com/{username}",
        "behance": f"https://www.behance.net/{username}",
        'tiktok': f'https://www.tiktok.com/@{username}' }
except KeyboardInterrupt:
    print('\nThanks for using our tool')
    exit()